definitions:
  extensibleObject:
    type: object
    properties:
      prop1:
        type: integer
    additionalProperties:
      type: string
      format: int-or-string
swagger: "2.0"
info:
  title: Kusion
  version: v0.0.2
paths: {}
